### ISSUE TITLE
Hello, I'm not sure if you have seen my message, because I don't know how to use guthub. The time difference makes it difficult for us to communicate (helpless). If you see any trouble, please answer my question. Thank you very much!

### ISSUE THREAD

**Issue by LUOXI23333** [Outrider305/Trident_Nevermore_Bed_Fans#1]
Hello, I'm not sure if you have seen my message, because I don't know how to use guthub. The time difference makes it difficult for us to communicate (helpless). If you see any trouble, please answer my question. Thank you very much!
![Screenshot_2023-02-20-16-57-30-912_com android browser](https://user-images.githubusercontent.com/92515498/220603084-4b8b7551-9dbf-424d-9018-c59fc225597d.jpg)

**Comment by Outrider305** [comment]
I have added an email for github questions: outrider305@gmail.com. Closing this issue.
