### ISSUE TITLE
Cover issue - notch or cut is missing

### ISSUE THREAD

**Issue by blonestar** [Outrider305/Trident_Nevermore_Bed_Fans#2]
Hey,
I found small issue with a fan cover, the place in the middle missing a cutout or a notch to be able to fit properly.
I've had to cut that with a knife, a scalpel. Now it fits. :)
![image](https://user-images.githubusercontent.com/5240133/225283023-e9d88a0e-11e9-4215-b641-917bf515e49d.png)
![20230315_113403](https://user-images.githubusercontent.com/5240133/225283610-2290aa15-6a1c-4516-bbe3-042589a030c5.jpg)
![20230315_113431](https://user-images.githubusercontent.com/5240133/225283653-c9831290-9829-4b27-b13f-ad6951c822c8.jpg)

Did not mount it yet but thank you for the mod. :)

**Comment by Outrider305** [comment]
Thanks for the heads up! Didn't realize there was a conflict, but I've been using the nevermores with that little lip still there without a problem. I've uploaded a revised plenum lid.

**Comment by blonestar** [comment]
Np. I've realized when I've put both nvrm sides on the table and one side was a bit higher.
Also I didn't have time to do that in CAD myself and I already printed same thing twice.
But thank you for quick fix and reply. :)
