### ISSUE TITLE
Plenum lid heatset insert cutout

### ISSUE THREAD

**Issue by btoconnor** [Outrider305/Trident_Nevermore_Bed_Fans#3]
Thanks for this mod. Getting ready to install it on my Trident.

I noticed when putting in the M3 heatset inserts into the parts last night, that the heatset insert space on the Plenum to secure the lid seemed like it was mis-shaped.  The heatset insert didn't "seat" properly into the hole, and there didn't seem to be enough room for the plastic to settle when the heatset insert was placed (a little sloppily, admittedly, because it was harder to do).

This resulted in a noticeable lip in displaced plastic above the heatset insert that I'll have to cut away, and the M3x16 won't go all the way into the heatset insert (I assume there's plastic stuck in the heatset that I'll drill out)

I'm not sure if this is an issue with my print (though none of the other holes on any of the parts had any issues), the base Nevermore project, this mod, or just random bad luck but figured I'd open the issue.

Here's a picture of the part as it stands before any drilling / cutting - the screw is in as far as I can insert it by hand:
![PXL_20230511_114906067](https://github.com/Outrider305/Trident_Nevermore_Bed_Mount/assets/81829/d9739def-bd72-4f3f-843f-6e12f81d1444)

**Comment by btoconnor** [comment]
I downloaded the f3z file and was able to look at it a little more closely (should have done that first I guess - pretty new to all of this)

It looks like the heatset insert hole diameter for the cartridge is 4.7mm - this one fit fine with zero issues.
The hole for the plenum heatset insert is showing as 3.2mm - which I think would explain the issue here.

I haven't gotten a chance to go through the CAD files for the nevermore base project, and I'm not sure how much of these objects are just slightly tweaked vs redesigns.

**Comment by btoconnor** [comment]
Okay - I think I might have an idea what happened. I opened the f3z file for the Nevermore project's plenum, and the hole in question here is 3.2mm.  However - it seems that it's a passthrough hole to a heatset insert that sits below it.  In this project's plenum, that opening does not exist, and there is no heatset insert to sit below the 3.2mm opening.

<img width="524" alt="image" src="https://github.com/Outrider305/Trident_Nevermore_Bed_Mount/assets/81829/7391f720-9411-4183-8a05-5c680d6bd780">

I think that simply making this hole on the plenum in this project to 4.7mm should solve the issue described.  I did a quick hack job here to expand it to 4.7mm and I'll try and print it out today and see if it resolves my issue.

Definitely let me know if I'm misunderstanding something fundamental though!

**Comment by btoconnor** [comment]
Update: I printed out the plenum with the heatset insert for the lid at 4.7mm rather than 3.2mm and it works perfectly.  I'd be happy to submit a PR, but I'm not so great with CAD and I don't think I'd be able to sufficiently commit the change back to the f3z file since importing it seemed like it didn't contain any of the original sequence.  Let me know if and how this should be continued if desired.

Thanks again for creating this mod!

**Comment by Outrider305** [comment]
> Update: I printed out the plenum with the heatset insert for the lid at 4.7mm rather than 3.2mm and it works perfectly.  I'd be happy to submit a PR, but I'm not so great with CAD and I don't think I'd be able to sufficiently commit the change back to the f3z file since importing it seemed like it didn't contain any of the original sequence.  Let me know if and how this should be continued if desired.
> 
> 
> 
> Thanks again for creating this mod! 

Hey. I'm so sorry I didn't see your messages earlier. I took a long break from 3d printing and I'm just getting back into it. 

So I removed that headset in the triangular cutout from the plenum. That heatset is meant to retain the vertical mounting point from the original nevermore v5. I replaced that heatset location with the 4.7mm hole on the outside of the plenum. It's meant to secure the plenum to the bracket. 

The 3.2mm hole that you put a heatset insert into is for the screw that retains the lid, but it doesn't take a heatset insert. The lid screw just threads into bare plastic.
